# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVXPatternsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVXPatternsDemo
  pod 'ReactiveObjC', :git => 'https://gitee.com/dingjiarui/ReactiveObjC.git'

end
